### ISSUE TITLE
Not highlights operator

### ISSUE THREAD

**Issue by xlaywan** [atom/base16-tomorrow-dark-theme#13]
For example in JS the `new` operator highlighted by regular color.

```
&.operator {
  color: @syntax-text-color;
}
```

Maybe it should be `@purple`?

**Comment by simurai** [comment]
@xlaywan I think that's intended and it seems that the original TextMate theme also doesn't highlight `.keyword.operator`: https://tmtheme-editor.herokuapp.com/#!/editor/theme/Base16%20Tomorrow%20Dark

You could override it in your `styles.less` file with:

```less
.theme-base16-tomorrow-dark-theme atom-text-editor::shadow {
  .keyword.operator {
    color: #b294bb;
  }
}
```

Or if it only should change `new` and not every `operator`:

```less
.theme-base16-tomorrow-dark-theme atom-text-editor::shadow {
  .keyword.operator.new {
    color: #b294bb;
  }
}
```
