### ISSUE TITLE
How to remove underline Class name

### ISSUE THREAD

**Issue by edyywang** [atom/base16-tomorrow-dark-theme#18]
Hi 

I like this syntax a lot, but how to remove underline Class name? It's really painful to see it. 

Thanks

**Comment by izuzak** [comment]
Hey @edyywang -- you can tweak those styles in your styles.less file:

https://atom.io/docs/latest/using-atom-basic-customization#style-tweaks

For example, try adding this:

```css
atom-text-editor::shadow .entity.name.type { 
  text-decoration: none;
}
```
