### ISSUE TITLE
Guides and special characters are now very bright

### ISSUE THREAD

**Issue by AlexKvazos** [atom/base16-tomorrow-dark-theme#32]
Hello, after updating to atom v.1.11.1 the theme got weird with the guides and characters...
![screen shot 2016-10-11 at 18 18 47](https://cloud.githubusercontent.com/assets/4448627/19292100/401d2396-8fdf-11e6-916e-77c23b8631cf.png)

Basically now they are way brighter and I am unsure how to change their colors.

**Comment by simurai** [comment]
This got changed in https://github.com/atom/base16-tomorrow-dark-theme/pull/29

To change it back to the darker color, adding the the following to your `styles.less` should work:

```less
atom-text-editor::shadow {
  .invisible-character {
    color: #373b41;
  }
}
```
