### ISSUE TITLE
Indent guide is too bright

### ISSUE THREAD

**Issue by austinthecoder** [atom/base16-tomorrow-dark-theme#35]
The indent guide recently got brighter. How can I dim it more?

![screen shot 2016-11-14 at 12 33 55 pm](https://cloud.githubusercontent.com/assets/4664/20275467/ab729bac-aa66-11e6-815e-523d736a3e09.png)

**Comment by simurai** [comment]
Yeah, they now use the "official" color for guides. But you can change it and make it darker by adding something like below in your `styles.less` file.

```less
atom-text-editor::shadow .indent-guide,
atom-text-editor .indent-guide {
  color: hsl(204, 2%, 25%);
}
```

Tweaking the last % number (`25%`) makes it darker or lighter.
