### ISSUE TITLE
[Suggestion] Update line wrap guide, highlight, and invisibles to be less bright

### ISSUE THREAD

**Issue by mikebronner** [atom/base16-tomorrow-dark-theme#42]
I have read the previous issues on the conflict between highlight area, and invisibles ( #32 along with PR #29 ), as well as the cursor hiding behind the line wrap indicator ( #16  which appears to have resurfaced).

Could I propose the following change to help satisfy all of these issues as once:
```less
atom-text-editor::shadow {
    .invisible-character {
        opacity: 0.5;
    }

    .selection .region {
        border-radius: 3px;
        opacity: 0.5;
    }

    .wrap-guide {
        opacity: 0.5;
    }
}
```

Thank you! :)

PS: the highlight border radius is just a personal preference.
